spring.application.name=productCatalogService

##DB Configration
spring.datasource.url=jdbc:postgresql://localhost:5432/product_catalog_service
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

##Flyway Config

spring.flyway.enabled=true
